In [ ]:
import pandas as pd

df = pd.read_csv('../data/perishable_goods_management.csv')
df.head(20) # Output the first 20 records

,record_id,product_id,product_name,category,store_id,region,supplier_id,transaction_date,expiration_date,shelf_life_days,...,selling_price,units_sold,units_wasted,waste_pct,revenue,waste_cost,profit,profit_margin_pct,supplier_score,is_promoted
0,1,BAK_DON_743,Donuts,Bakery,STORE_046,West,SUPPLIER_03,2024-09-25,2024-09-29,4,...,2.60,138,20,12.7,358.80,24.40,166.04,46.3,9,0
1,2,MEA_SAU_338,Sausages,Meat,STORE_030,Southwest,SUPPLIER_12,2023-04-14,2023-04-21,9,...,8.25,251,102,28.9,2070.75,426.36,595.21,28.7,6,0
2,3,BAK_BAG_799,Bagels,Bakery,STORE_035,Midwest,SUPPLIER_08,2024-10-25,2024-10-27,2,...,1.28,483,0,0.0,618.24,0.00,-405.72,-65.6,9,0
3,4,PHA_VAC_801,Vaccines,Pharmaceuticals,STORE_003,Midwest,SUPPLIER_11,2023-11-29,2024-02-17,87,...,209.56,477,0,0.0,99960.12,0.00,57988.89,58.0,6,0
4,5,REA_FRE_422,Fresh Pasta,Ready_to_Eat,STORE_042,West,SUPPLIER_15,2023-08-06,2023-08-09,4,...,5.28,391,0,0.0,2064.48,0.00,879.75,42.6,6,0
5,6,PHA_EYE_369,Eye Drops,Pharmaceuticals,STORE_026,West,SUPPLIER_12,2024-08-21,2025-07-06,468,...,121.37,0,270,100.0,0.00,22914.90,-22914.90,0.0,6,0
6,7,BEV_FRE_873,Fresh Juice,Beverages,STORE_041,Midwest,SUPPLIER_06,2023-02-18,2023-02-27,10,...,8.34,41,1,2.4,341.94,4.39,157.56,46.1,8,0
7,8,FRO_FRO_710,Frozen Dinners,Frozen_Meals,STORE_036,Northeast,SUPPLIER_01,2024-04-24,2025-02-16,330,...,14.88,0,463,100.0,0.00,2990.98,-2990.98,0.0,7,0
8,9,PHA_ANT_887,Antibiotics,Pharmaceuticals,STORE_019,Northeast,SUPPLIER_14,2024-10-18,2025-10-17,378,...,91.71,379,0,0.0,34758.09,0.00,20822.26,59.9,6,0
9,10,BAK_CRO_880,Croissants,Bakery,STORE_041,Midwest,SUPPLIER_10,2023-07-02,2023-07-08,6,...,12.94,111,0,0.0,1436.34,0.00,642.69,44.7,8,0
10,11,SEA_TUN_880,Tuna,Seafood,STORE_001,Northeast,SUPPLIER_20,2023-06-15,2023-06-19,6,...,19.99,257,228,47.0,5137.43,1849.08,1204.08,23.4,9,0
11,12,DEL_SAL_345,Salami,Deli,STORE_006,Southeast,SUPPLIER_03,2023-03-01,2023-03-05,6,...,14.25,279,120,30.1,3975.75,1102.80,308.94,7.8,9,0
12,13,PHA_VAC_231,Vaccines,Pharmaceuticals,STORE_011,Southwest,SUPPLIER_09,2024-11-06,2025-11-17,516,...,211.32,118,0,0.0,24935.76,0.00,6330.70,25.4,8,0
13,14,PHA_BIO_806,Biologics,Pharmaceuticals,STORE_043,Midwest,SUPPLIER_12,2023-07-25,2024-05-18,349,...,227.48,0,71,100.0,0.00,8968.01,-8968.01,0.0,6,0
14,15,PRO_TOM_165,Tomatoes,Produce,STORE_038,Southwest,SUPPLIER_08,2023-12-13,2023-12-16,3,...,0.85,40,0,0.0,34.00,0.00,8.40,24.7,9,0
15,16,PRO_LET_132,Lettuce,Produce,STORE_018,West,SUPPLIER_16,2023-12-05,2023-12-10,5,...,2.50,488,0,0.0,1220.00,0.00,683.20,56.0,10,0
16,17,REA_SOU_584,Soups,Ready_to_Eat,STORE_013,Northeast,SUPPLIER_04,2023-09-06,2023-09-09,4,...,2.00,226,0,0.0,452.00,0.00,-296.06,-65.5,9,1
17,18,FRO_FRO_984,Frozen Dinners,Frozen_Meals,STORE_026,West,SUPPLIER_11,2023-02-25,2023-06-12,110,...,16.81,103,5,4.6,1731.43,36.40,945.19,54.6,6,0
18,19,PRO_BER_559,Berries,Produce,STORE_018,West,SUPPLIER_15,2023-05-24,2023-06-08,16,...,2.75,236,0,0.0,649.00,0.00,210.04,32.4,6,0
19,20,PHA_INS_151,Insulin,Pharmaceuticals,STORE_006,Southeast,SUPPLIER_08,2024-10-29,2026-06-01,583,...,95.66,119,0,0.0,11383.54,0.00,5171.74,45.4,9,1

In [3]:
import pandas as pd

df = pd.read_csv('../data/perishable_goods_management.csv')
df.head(50)

,record_id,product_id,product_name,category,store_id,region,supplier_id,transaction_date,expiration_date,shelf_life_days,...,selling_price,units_sold,units_wasted,waste_pct,revenue,waste_cost,profit,profit_margin_pct,supplier_score,is_promoted
0,1,BAK_DON_743,Donuts,Bakery,STORE_046,West,SUPPLIER_03,2024-09-25,2024-09-29,4,...,2.60,138,20,12.7,358.80,24.40,166.04,46.3,9,0
1,2,MEA_SAU_338,Sausages,Meat,STORE_030,Southwest,SUPPLIER_12,2023-04-14,2023-04-21,9,...,8.25,251,102,28.9,2070.75,426.36,595.21,28.7,6,0
2,3,BAK_BAG_799,Bagels,Bakery,STORE_035,Midwest,SUPPLIER_08,2024-10-25,2024-10-27,2,...,1.28,483,0,0.0,618.24,0.00,-405.72,-65.6,9,0
3,4,PHA_VAC_801,Vaccines,Pharmaceuticals,STORE_003,Midwest,SUPPLIER_11,2023-11-29,2024-02-17,87,...,209.56,477,0,0.0,99960.12,0.00,57988.89,58.0,6,0
4,5,REA_FRE_422,Fresh Pasta,Ready_to_Eat,STORE_042,West,SUPPLIER_15,2023-08-06,2023-08-09,4,...,5.28,391,0,0.0,2064.48,0.00,879.75,42.6,6,0
5,6,PHA_EYE_369,Eye Drops,Pharmaceuticals,STORE_026,West,SUPPLIER_12,2024-08-21,2025-07-06,468,...,121.37,0,270,100.0,0.00,22914.90,-22914.90,0.0,6,0
6,7,BEV_FRE_873,Fresh Juice,Beverages,STORE_041,Midwest,SUPPLIER_06,2023-02-18,2023-02-27,10,...,8.34,41,1,2.4,341.94,4.39,157.56,46.1,8,0
7,8,FRO_FRO_710,Frozen Dinners,Frozen_Meals,STORE_036,Northeast,SUPPLIER_01,2024-04-24,2025-02-16,330,...,14.88,0,463,100.0,0.00,2990.98,-2990.98,0.0,7,0
8,9,PHA_ANT_887,Antibiotics,Pharmaceuticals,STORE_019,Northeast,SUPPLIER_14,2024-10-18,2025-10-17,378,...,91.71,379,0,0.0,34758.09,0.00,20822.26,59.9,6,0
9,10,BAK_CRO_880,Croissants,Bakery,STORE_041,Midwest,SUPPLIER_10,2023-07-02,2023-07-08,6,...,12.94,111,0,0.0,1436.34,0.00,642.69,44.7,8,0
10,11,SEA_TUN_880,Tuna,Seafood,STORE_001,Northeast,SUPPLIER_20,2023-06-15,2023-06-19,6,...,19.99,257,228,47.0,5137.43,1849.08,1204.08,23.4,9,0
11,12,DEL_SAL_345,Salami,Deli,STORE_006,Southeast,SUPPLIER_03,2023-03-01,2023-03-05,6,...,14.25,279,120,30.1,3975.75,1102.80,308.94,7.8,9,0
12,13,PHA_VAC_231,Vaccines,Pharmaceuticals,STORE_011,Southwest,SUPPLIER_09,2024-11-06,2025-11-17,516,...,211.32,118,0,0.0,24935.76,0.00,6330.70,25.4,8,0
13,14,PHA_BIO_806,Biologics,Pharmaceuticals,STORE_043,Midwest,SUPPLIER_12,2023-07-25,2024-05-18,349,...,227.48,0,71,100.0,0.00,8968.01,-8968.01,0.0,6,0
14,15,PRO_TOM_165,Tomatoes,Produce,STORE_038,Southwest,SUPPLIER_08,2023-12-13,2023-12-16,3,...,0.85,40,0,0.0,34.00,0.00,8.40,24.7,9,0
15,16,PRO_LET_132,Lettuce,Produce,STORE_018,West,SUPPLIER_16,2023-12-05,2023-12-10,5,...,2.50,488,0,0.0,1220.00,0.00,683.20,56.0,10,0
16,17,REA_SOU_584,Soups,Ready_to_Eat,STORE_013,Northeast,SUPPLIER_04,2023-09-06,2023-09-09,4,...,2.00,226,0,0.0,452.00,0.00,-296.06,-65.5,9,1
17,18,FRO_FRO_984,Frozen Dinners,Frozen_Meals,STORE_026,West,SUPPLIER_11,2023-02-25,2023-06-12,110,...,16.81,103,5,4.6,1731.43,36.40,945.19,54.6,6,0
18,19,PRO_BER_559,Berries,Produce,STORE_018,West,SUPPLIER_15,2023-05-24,2023-06-08,16,...,2.75,236,0,0.0,649.00,0.00,210.04,32.4,6,0
19,20,PHA_INS_151,Insulin,Pharmaceuticals,STORE_006,Southeast,SUPPLIER_08,2024-10-29,2026-06-01,583,...,95.66,119,0,0.0,11383.54,0.00,5171.74,45.4,9,1
20,21,FRO_PIZ_268,Pizza,Frozen_Meals,STORE_017,West,SUPPLIER_15,2024-01-24,2024-03-13,61,...,6.51,384,0,0.0,2499.84,0.00,499.20,20.0,6,0
21,22,PHA_BIO_835,Biologics,Pharmaceuticals,STORE_019,Northeast,SUPPLIER_07,2024-05-13,2024-11-05,188,...,484.82,200,87,30.3,96964.00,24200.79,17129.21,17.7,9,0
22,23,DAI_COT_421,Cottage Cheese,Dairy,STORE_031,Midwest,SUPPLIER_17,2023-02-28,2023-03-04,6,...,8.17,20,19,48.7,163.40,118.94,-80.74,-49.4,9,0
23,24,PHA_INS_971,Insulin,Pharmaceuticals,STORE_044,Northeast,SUPPLIER_08,2023-07-10,2023-10-14,100,...,210.83,301,0,0.0,63459.83,0.00,20148.94,31.8,9,0
24,25,PRO_BER_708,Berries,Produce,STORE_043,Midwest,SUPPLIER_19,2023-02-10,2023-02-14,5,...,3.67,98,45,31.5,359.66,110.25,9.31,2.6,10,0
25,26,PRO_AVO_833,Avocados,Produce,STORE_026,West,SUPPLIER_05,2023-11-18,2023-11-26,10,...,5.70,171,0,0.0,974.70,0.00,497.61,51.1,10,1
26,27,MEA_BEE_569,Beef,Meat,STORE_035,Midwest,SUPPLIER_07,2024-09-28,2024-10-02,4,...,15.12,131,57,30.3,1980.72,379.05,730.52,36.9,9,0
27,28,MEA_CHI_478,Chicken,Meat,STORE_035,Midwest,SUPPLIER_10,2023-10-19,2023-10-23,5,...,8.79,158,186,54.1,1388.82,2232.00,-2739.18,-197.2,8,0
28,29,PHA_INS_783,Insulin,Pharmaceuticals,STORE_007,Northeast,SUPPLIER_05,2024-07-21,2025-03-30,336,...,143.27,0,390,100.0,0.00,37264.50,-37264.50,0.0,10,0
29,30,PHA_VAC_378,Vaccines,Pharmaceuticals,STORE_046,West,SUPPLIER_11,2023-10-16,2025-06-03,649,...,113.74,0,145,100.0,0.00,9735.30,-9735.30,0.0,6,0
30,31,PHA_PRO_357,Probiotics,Pharmaceuticals,STORE_028,Northeast,SUPPLIER_09,2023-02-22,2023-05-17,124,...,36.38,76,0,0.0,2764.88,0.00,1382.44,50.0,8,1
31,32,BAK_PAS_859,Pastries,Bakery,STORE_028,Northeast,SUPPLIER_18,2024-03-28,2024-04-01,6,...,1.62,343,119,25.8,555.66,107.10,139.86,25.2,8,0
32,33,SEA_CRA_136,Crab,Seafood,STORE_010,West,SUPPLIER_14,2024-01-14,2024-01-18,6,...,12.72,329,141,30.0,4184.88,882.66,1242.68,29.7,6,1
33,34,DAI_YOG_315,Yogurt,Dairy,STORE_023,Southwest,SUPPLIER_18,2024-11-29,2024-12-11,12,...,10.84,228,99,30.3,2471.52,560.34,620.70,25.1,8,0
34,35,SEA_SHR_985,Shrimp,Seafood,STORE_002,Northeast,SUPPLIER_06,2023-06-16,2023-06-18,3,...,14.81,486,0,0.0,7197.66,0.00,-1360.80,-18.9,8,0
35,36,FRO_ICE_373,Ice Cream,Frozen_Meals,STORE_003,Midwest,SUPPLIER_16,2023-06-13,2023-09-12,115,...,7.56,160,85,34.7,1209.60,414.80,14.00,1.2,10,0
36,37,DEL_SAL_940,Salami,Deli,STORE_043,Midwest,SUPPLIER_07,2023-08-22,2023-08-28,6,...,9.58,35,10,22.2,335.30,46.30,126.95,37.9,9,0
37,38,BAK_CAK_756,Cakes,Bakery,STORE_002,Northeast,SUPPLIER_04,2024-06-05,2024-06-09,5,...,13.40,307,0,0.0,4113.80,0.00,2145.93,52.2,9,0
38,39,BAK_BRE_211,Bread,Bakery,STORE_047,Northeast,SUPPLIER_11,2024-09-02,2024-09-06,5,...,5.52,34,35,50.7,187.68,186.55,-180.09,-96.0,6,0
39,40,FRO_FRO_294,Frozen Desserts,Frozen_Meals,STORE_028,Northeast,SUPPLIER_01,2023-09-18,2023-11-17,82,...,12.32,361,0,0.0,4447.52,0.00,1592.01,35.8,7,0
40,41,PRO_BAN_541,Bananas,Produce,STORE_021,Southeast,SUPPLIER_04,2023-03-13,2023-03-22,13,...,6.04,121,47,28.0,730.84,139.12,233.56,32.0,9,0
41,42,FRO_FRO_512,Frozen Vegetables,Frozen_Meals,STORE_009,Northeast,SUPPLIER_07,2024-12-14,2025-05-04,211,...,10.73,101,255,71.6,1083.73,1866.60,-1522.19,-140.5,9,1
42,43,SEA_CRA_682,Crab,Seafood,STORE_020,West,SUPPLIER_10,2023-11-05,2023-11-10,5,...,12.94,272,48,15.0,3519.68,481.44,310.08,8.8,8,0
43,44,DEL_PRE_552,Prepared Salads,Deli,STORE_033,Southeast,SUPPLIER_16,2024-03-28,2024-04-09,13,...,15.11,270,116,30.1,4079.70,1205.24,69.16,1.7,10,0
44,45,SEA_LOB_186,Lobster,Seafood,STORE_041,Midwest,SUPPLIER_20,2023-10-18,2023-10-22,6,...,12.04,167,227,57.6,2010.68,2989.59,-3178.30,-158.1,9,1
45,46,PRO_AVO_417,Avocados,Produce,STORE_002,Northeast,SUPPLIER_02,2023-08-19,2023-08-27,9,...,2.71,445,0,0.0,1205.95,0.00,551.80,45.8,7,1
46,47,MEA_LAM_524,Lamb,Meat,STORE_045,Southwest,SUPPLIER_13,2024-10-06,2024-10-10,6,...,12.51,172,173,50.1,2151.72,1219.65,-280.53,-13.0,10,0
47,48,DAI_SOU_981,Sour Cream,Dairy,STORE_015,Southeast,SUPPLIER_06,2023-04-20,2023-05-13,29,...,10.04,247,0,0.0,2479.88,0.00,970.71,39.1,8,0
48,49,DAI_CRE_355,Cream,Dairy,STORE_030,Southwest,SUPPLIER_17,2023-05-05,2023-05-23,19,...,11.88,496,0,0.0,5892.48,0.00,2484.96,42.2,9,0
49,50,BEV_MIL_934,Milk Alternatives,Beverages,STORE_036,Northeast,SUPPLIER_15,2024-05-31,2024-06-14,20,...,9.18,202,51,20.2,1854.36,291.72,407.20,22.0,6,1